### ISSUE TITLE
tagily: a system to compare against

### ISSUE THREAD

**Issue by francescosolera** [alexcu/hermes-bib-detect#5]
Hi Alex,
great repo indeed. I've also read your thesis with great interest.

If you're still working in this field, you might be interested in [tagily.io](https://tagily.io), a cloud-based service for automatic bib number recognition in sport events we recently released.

We also use deep learning (no secret) to detect and recognize bibs! If you want to compare the results of your future research, please let me know: we'll be happy to provide you results for free.

It's super easy to use and you'll have the results in a few minutes after you start uploading the pictures. We also provide a convenient upload tool. Depending on your internet connection speed, we can process up to 10.000 images per hour.

You can use it on all types of bibs, no additional code placement is required (e.g. QR or Aruco code), because we read the number directly. We don't even have camera requirements: as long as the bib number is good enough for a human to read it, our artificial intelligence system can also read it.

As of today, our biggest event has been the Marcialonga 2018, where 100.000 images were processed in one night. Yet the software smoothly works for marathons and bike races as well. You can learn more about it here: [http://www.deepvisionconsulting.com/automatic-bib-recognition-kick-off-at-marcialonga-2018](http://www.deepvisionconsulting.com/automatic-bib-recognition-kick-off-at-marcialonga-2018) or just go to the website to ask for a free trial: [https://tagily.io](https://tagily.io).

Best regards,
Francesco

**Comment by alexcu** [comment]
Hi @francescosolera, sorry for the delay. I wasn't aware/notified that anyone was actually interested in the work until now, so thanks for the positive feedback!

If you're still interested in talking further, please email me at ca@deakin.edu.au.

Best wishes,
Alex
