### ISSUE TITLE
Pickle config file

### ISSUE THREAD

**Issue by mrtrunghieu1** [alexcu/hermes-bib-detect#7]
When I'm running detect.py it requirement "/path/to/pickle.config" ???
I can't find pickle.config.
Can u help me,please?

**Comment by alexcu** [comment]
Hi @mrtrunghieu1 (also @minhnd1 referring to #6)... sorry for the delay (wasn't aware people were interested in this repo!).

The pickle files are generated from the relevant training utilities (see https://github.com/alexcu/hermes-training-utils). You need two pickle models (one for bibs and one for text). 

To make life easier for you, I've hunted down where these config files have gone and uploaded them for you. Please see:

- http://deakin.edu.au/~ca/alphanum/models/bib_config.pickle
- http://deakin.edu.au/~ca/alphanum/models/bib_model_18-08-2017_frcnn.hdf5
- http://deakin.edu.au/~ca/alphanum/models/text_config.pickle
- http://deakin.edu.au/~ca/alphanum/models/text_model_31-08-2017_frcnn.hdf5

Note: You will need to modify the pickle files to change where the .hdf5 point is, i.e. change the directory under line 88 of the pickle files:

```
p32
S'/path/to/text_model_31-08-2017_frcnn.hdf5'
```

to wherever you have stored the pre-trained hdf5 files.

Good luck!

**Comment by alexcu** [comment]
Links above are broken, see #8 for the updated links.
