### ISSUE TITLE
Pickle config file

### ISSUE THREAD

**Issue by charlotteburki** [alexcu/hermes-bib-detect#8]
Hi Alex, 

I was looking for the different pickle files. I saw in the closed issues that you gave different links to download them. Unfortunately the links don't work anymore. Would it be possible to reshare the files with me?

Thanks a lot and have a nice day!

**Comment by alexcu** [comment]
Hi @charlotteburki,

Thanks for the update… it seems the University migrated to a new subdomain for staff webpages and so the links from #7 no longer forward correctly.

Here are the updated links:

- https://personal-sites.deakin.edu.au/~ca/alphanum/models/bib_config.pickle
- https://personal-sites.deakin.edu.au/~ca/alphanum/models/bib_model_18-08-2017_frcnn.hdf5
- https://personal-sites.deakin.edu.au/~ca/alphanum/models/text_config.pickle
- https://personal-sites.deakin.edu.au/~ca/alphanum/models/text_model_31-08-2017_frcnn.hdf5

Enjoy!

Thanks,
Alex

**Comment by charlotteburki** [comment]
Great, many thanks!
